-- FamousPeople.id MVP Schema
-- Run in Supabase SQL Editor

-- Extensions
create extension if not exists vector;
create extension if not exists pg_trgm;

-- Lookup table for relation types
create table public.relation_types (
  code text primary key,
  label text not null,
  reverse_label text
);

insert into relation_types (code, label, reverse_label) values
  ('spouse', 'Spouse', 'Spouse'),
  ('ex_spouse', 'Ex-Spouse', 'Ex-Spouse'),
  ('dated', 'Dated', 'Dated'),
  ('parent', 'Parent', 'Child'),
  ('child', 'Child', 'Parent'),
  ('sibling', 'Sibling', 'Sibling'),
  ('colleague', 'Colleague', 'Colleague'),
  ('mentor', 'Mentor', 'Mentee'),
  ('rival', 'Rival', 'Rival'),
  ('founder', 'Founder', 'Founded By'),
  ('member', 'Member Of', 'Has Member'),
  ('collaborator', 'Collaborator', 'Collaborator'),
  ('unknown', 'Unknown', 'Unknown');

-- Main identities table
create table public.identities (
  fpid text primary key,
  slug text unique not null,
  full_name text not null,
  type text not null default 'Person' check (type in ('Person', 'Organization', 'Band', 'Group')),
  net_worth bigint check (net_worth >= 0),
  height_cm int check (height_cm between 50 and 300),
  birth_date date,
  death_date date,
  country text[] default '{}',
  mbti text check (mbti is null or mbti ~ '^[EI][NS][TF][JP]$'),
  zodiac text check (zodiac is null or zodiac in ('Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces')),
  gender text check (gender is null or gender in ('male', 'female', 'non-binary', 'other')),
  occupation text[],
  image_url text,
  wikipedia_url text,
  social_links jsonb default '{}'::jsonb,
  meta jsonb default '{}'::jsonb,
  bio_summary text,
  content_md text,
  embedding vector(1536),
  is_published boolean default false,
  -- Indexing strategy (drip-feed)
  fame_tier text check (fame_tier is null or fame_tier in ('S', 'A', 'B', 'C')),
  sitelinks int default 0,  -- Wikipedia article count from Wikidata
  -- Data provenance (E-E-A-T)
  data_sources jsonb default '{}'::jsonb,  -- {"net_worth": {"source": "Forbes", "date": "2026-01"}}
  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  constraint valid_dates check (death_date is null or birth_date is null or death_date > birth_date)
);

-- Relationships table
create table public.relationships (
  id bigint generated by default as identity primary key,
  source_fpid text not null references identities(fpid) on delete cascade,
  target_fpid text not null references identities(fpid) on delete cascade,
  relation_type text not null references relation_types(code),
  start_date date,
  end_date date,
  details jsonb default '{}'::jsonb,
  created_at timestamptz default now(),

  constraint no_self_relation check (source_fpid != target_fpid),
  constraint unique_relationship unique(source_fpid, target_fpid, relation_type)
);

-- Indexes: identities
create index idx_identities_slug on identities(slug);
create index idx_identities_full_name_trgm on identities using gin (full_name gin_trgm_ops);
create index idx_identities_type on identities(type) where type != 'Person';
create index idx_identities_net_worth on identities(net_worth desc nulls last) where net_worth is not null;
create index idx_identities_birth_date on identities(birth_date) where birth_date is not null;
create index idx_identities_country on identities using gin (country);
create index idx_identities_occupation on identities using gin (occupation);
create index idx_identities_published on identities(is_published, updated_at desc);
create index idx_identities_embedding on identities using hnsw (embedding vector_cosine_ops);
create index idx_identities_fame_tier on identities(fame_tier, is_published);  -- Drip-feed indexing

-- Indexes: relationships (FK indexes critical)
create index idx_relationships_source on relationships(source_fpid);
create index idx_relationships_target on relationships(target_fpid);
create index idx_relationships_type on relationships(relation_type);

-- Auto-update timestamp trigger
create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger trg_identities_updated_at
  before update on identities
  for each row execute function update_updated_at();

-- Row Level Security
alter table identities enable row level security;
alter table relationships enable row level security;
alter table relation_types enable row level security;

-- Public: read published only
create policy "Public read published identities"
  on identities for select
  using (is_published = true);

-- Authenticated: read all
create policy "Authenticated read all identities"
  on identities for select
  to authenticated
  using (true);

-- Service role: full access
create policy "Service role full access identities"
  on identities for all
  to service_role
  using (true)
  with check (true);

-- Relationships: public read via published
create policy "Public read relationships"
  on relationships for select
  using (
    exists (select 1 from identities where fpid = source_fpid and is_published = true)
    and exists (select 1 from identities where fpid = target_fpid and is_published = true)
  );

-- Service role relationships
create policy "Service role full access relationships"
  on relationships for all
  to service_role
  using (true)
  with check (true);

-- Relation types: public read
create policy "Public read relation types"
  on relation_types for select
  using (true);

create policy "Service role full access relation_types"
  on relation_types for all
  to service_role
  using (true)
  with check (true);

-- RPC: Search people with trigram relevance
create or replace function public.search_people(
  q text,
  type_filter text default 'Person',
  country_filter text default null,
  occupation_filter text default null,
  zodiac_filter text default null,
  mbti_filter text default null,
  gender_filter text default null,
  birth_year_min int default null,
  birth_year_max int default null,
  net_worth_min bigint default null,
  is_alive boolean default null,
  sort text default 'relevance',
  limit_count int default 20,
  offset_count int default 0
)
returns table (
  fpid text,
  slug text,
  full_name text,
  net_worth bigint,
  height_cm int,
  birth_date date,
  occupation text[],
  country text[],
  zodiac text,
  mbti text,
  image_url text,
  relevance_score real
)
language sql stable as $$
  with base as (
    select
      fpid, slug, full_name, net_worth, occupation, image_url,
      similarity(full_name, q) as relevance_score,
      birth_date,
      country,
      zodiac,
      mbti,
      gender,
      death_date,
      type
    from identities
    where is_published = true
      and (q is null or full_name % q)
      and (type_filter is null or type = type_filter)
      and (country_filter is null or country_filter = any(country))
      and (occupation_filter is null or occupation_filter = any(occupation))
      and (zodiac_filter is null or zodiac = zodiac_filter)
      and (mbti_filter is null or mbti = mbti_filter)
      and (gender_filter is null or gender = gender_filter)
      and (birth_year_min is null or extract(year from birth_date) >= birth_year_min)
      and (birth_year_max is null or extract(year from birth_date) <= birth_year_max)
      and (net_worth_min is null or net_worth >= net_worth_min)
      and (is_alive is null or (is_alive = true and death_date is null) or (is_alive = false and death_date is not null))
  )
  select fpid, slug, full_name, net_worth, height_cm, birth_date, occupation, country, zodiac, mbti, image_url, relevance_score
  from base
  order by
    case when sort = 'relevance' then relevance_score end desc nulls last,
    case when sort = 'net_worth:desc' then net_worth end desc nulls last,
    case when sort = 'birth_date:asc' then birth_date end asc nulls last,
    case when sort = 'name:asc' then full_name end asc
  limit limit_count offset offset_count;
$$;

create or replace function public.search_people_count(
  q text,
  type_filter text default 'Person',
  country_filter text default null,
  occupation_filter text default null,
  zodiac_filter text default null,
  mbti_filter text default null,
  gender_filter text default null,
  birth_year_min int default null,
  birth_year_max int default null,
  net_worth_min bigint default null,
  is_alive boolean default null
)
returns bigint
language sql stable as $$
  select count(*) from identities
  where is_published = true
    and (q is null or full_name % q)
    and (type_filter is null or type = type_filter)
    and (country_filter is null or country_filter = any(country))
    and (occupation_filter is null or occupation_filter = any(occupation))
    and (zodiac_filter is null or zodiac = zodiac_filter)
    and (mbti_filter is null or mbti = mbti_filter)
    and (gender_filter is null or gender = gender_filter)
    and (birth_year_min is null or extract(year from birth_date) >= birth_year_min)
    and (birth_year_max is null or extract(year from birth_date) <= birth_year_max)
    and (net_worth_min is null or net_worth >= net_worth_min)
    and (is_alive is null or (is_alive = true and death_date is null) or (is_alive = false and death_date is not null));
$$;

create or replace function public.search_people_facets(
  q text,
  type_filter text default 'Person',
  country_filter text default null,
  occupation_filter text default null,
  zodiac_filter text default null,
  mbti_filter text default null,
  gender_filter text default null,
  birth_year_min int default null,
  birth_year_max int default null,
  net_worth_min bigint default null,
  is_alive boolean default null
)
returns jsonb
language sql stable as $$
  with base as (
    select *
    from identities
    where is_published = true
      and (q is null or full_name % q)
      and (type_filter is null or type = type_filter)
      and (country_filter is null or country_filter = any(country))
      and (occupation_filter is null or occupation_filter = any(occupation))
      and (zodiac_filter is null or zodiac = zodiac_filter)
      and (mbti_filter is null or mbti = mbti_filter)
      and (gender_filter is null or gender = gender_filter)
      and (birth_year_min is null or extract(year from birth_date) >= birth_year_min)
      and (birth_year_max is null or extract(year from birth_date) <= birth_year_max)
      and (net_worth_min is null or net_worth >= net_worth_min)
      and (is_alive is null or (is_alive = true and death_date is null) or (is_alive = false and death_date is not null))
  ),
  country_facets as (
    select unnest(country) as value, count(*) as count
    from base
    where country is not null
    group by value
    order by count desc
    limit 20
  ),
  zodiac_facets as (
    select zodiac as value, count(*) as count
    from base
    where zodiac is not null
    group by zodiac
    order by count desc
    limit 20
  )
  select jsonb_build_object(
    'country', coalesce((select jsonb_agg(jsonb_build_object('value', value, 'count', count)) from country_facets), '[]'::jsonb),
    'zodiac', coalesce((select jsonb_agg(jsonb_build_object('value', value, 'count', count)) from zodiac_facets), '[]'::jsonb)
  );
$$;

-- RPC: Birthdays today
create or replace function public.get_birthdays_today(
  limit_count int default 100,
  offset_count int default 0
)
returns table (
  fpid text,
  slug text,
  full_name text,
  birth_date date,
  net_worth bigint,
  height_cm int,
  occupation text[],
  country text[],
  zodiac text,
  mbti text,
  image_url text
)
language sql stable as $$
  select fpid, slug, full_name, birth_date, net_worth, height_cm, occupation, country, zodiac, mbti, image_url
  from identities
  where is_published = true
    and birth_date is not null
    and extract(month from birth_date) = extract(month from current_date)
    and extract(day from birth_date) = extract(day from current_date)
  order by full_name asc
  limit limit_count offset offset_count;
$$;

-- RPC: Birthdays by month
create or replace function public.get_birthdays_month(
  month_num int,
  limit_count int default 200,
  offset_count int default 0
)
returns table (
  fpid text,
  slug text,
  full_name text,
  birth_date date,
  net_worth bigint,
  height_cm int,
  occupation text[],
  country text[],
  zodiac text,
  mbti text,
  image_url text
)
language sql stable as $$
  select fpid, slug, full_name, birth_date, net_worth, height_cm, occupation, country, zodiac, mbti, image_url
  from identities
  where is_published = true
    and birth_date is not null
    and extract(month from birth_date) = month_num
  order by birth_date asc
  limit limit_count offset offset_count;
$$;

-- Grants for RPC functions (public read)
grant execute on function public.search_people(text, text, text, text, text, text, text, int, int, bigint, boolean, text, int, int) to anon, authenticated;
grant execute on function public.search_people_count(text, text, text, text, text, text, text, int, int, bigint, boolean) to anon, authenticated;
grant execute on function public.search_people_facets(text, text, text, text, text, text, text, int, int, bigint, boolean) to anon, authenticated;
grant execute on function public.get_birthdays_today(int, int) to anon, authenticated;
grant execute on function public.get_birthdays_month(int, int, int) to anon, authenticated;
